<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_QuickOrder
 */
?>
<?php /** @var \Amasty\QuickOrder\Block\Script\Grouped $block */ ?>

<script type="text/x-magento-init">
{
    "[data-amqorder-js=\"item\"][data-item-id=\"<?= $block->escapeHtml($block->getItemId()) ?>\"] #super-product-table": {
        "Amasty_QuickOrder/js/catalog/subtotal/grouped-options": <?= /* @noEscape */ $block->getJsonConfig() ?>
    }
}
</script>
