<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_QuickOrder
 */
?>
<?php /** @var \Amasty\QuickOrder\Block\Script\Price $block */ ?>

<script>
    require([
        'jquery',
        'amqorderPriceBox'
    ], function($) {
        var dataQuickOrderItem = '[data-amqorder-js="item"][data-item-id=<?= $block->escapeHtml($block->getItemId()) ?>]',
            dataPriceBoxSelector = '[data-role=priceBox]'
            priceBoxes = $(dataQuickOrderItem + ' ' + dataPriceBoxSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @noEscape */ $block->getJsonConfig() ?> });
    });
</script>
