<?php
/** @var Details $block */

use Amasty\RequestQuote\Block\Cart\Quote\Details;
?>
<div id="quote-details" class="quote-details" data-bind="scope:'details'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#quote-details": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
    </script>
</div>
