<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MWishlist
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<?= $block->escapeHtml(
    __(
        '%1 has been moved to <a href="%2">%3</a>.',
        $block->getData('product_name'),
        $block->getData('wishlist_url'),
        $block->getData('wishlist_name')
    ),
    ['a']
);
