<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php	
	
    $_helper    = $this->helper(Magento\Catalog\Helper\Output::class);
    $_imgHtml   = '';
	$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
	$currentStore = $storeManager->getStore();
	$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	$categoryModel = $objectManager->create(\Magento\Catalog\Model\CategoryFactory::class);
	$currentCategory = $block->getCurrentCategory();
	$childrenIds = explode(',',$currentCategory->getChildren());
	$categories = [];
?>
<div class="row subcategories">
	<?php foreach ($childrenIds as $key => $child):
		$category = $categoryModel->create()->load($child);
		$categorieImage = $mediaUrl.'catalog/category/'.$category->getThumbnail();
		$categorieName = $category->getName();
		$categorieLink = $block->getBaseUrl().$category->getUrlPath(); 
		//$categorieImage = $category->getImageUrl(); ?>
		
	<?php //print_r($category);
	//die("sas");
    /*if ($_imgUrl = $currentCategory->getImageUrl()) {
        $_imgHtml = '<div class="category-image"><img src="'
            . $block->escapeUrl($_imgUrl)
            . '" alt="'
            . $block->escapeHtmlAttr($currentCategory->getName())
            . '" title="'
            . $block->escapeHtmlAttr($currentCategory->getName())
            . '" class="image" /></div>';
        $_imgHtml = $_helper->categoryAttribute($currentCategory, $_imgHtml, 'image');
        /* @noEscape *//* echo $_imgHtml;
    }*/?>
	<div class="item">
		<div class="item-inner">
			<div class="images-content">
				<a href="<?= $categorieLink ?>" title="<?= $categorieName ?>" class="sub-image product-image"><img src="<?= $categorieImage ?>" alt="<?= $categorieName ?>" /></a>
			</div>
			<div class="box-content">
				<h2 class="department-name"><a href="<?= $categorieLink ?>" title="<?= $categorieName ?>"><?= $categorieName ?></a></h2>				
			</div>	
		</div>
	</div>
<?php endforeach; ?>
</div>
<script type="text/javascript">
	require([
		'jquery'
	], function ($) {
		jQuery('body').addClass('page-subcategories');
	});		
</script>