<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div data-block="minicart-footer" class="minicart-footer-wrapper">

    <?php if ($block->getIsNeedToDisplaySideBar()):?>
        <div class="block block-minicart-footer">
            <div id="minicart-footer-content-wrapper" data-bind="scope: 'minicart_content_footer'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            
            <a class="action showcart-footer" href="javascript:void(0)"
               data-bind="scope: 'minicart_content_footer'">
                <span class="text"><?= $block->escapeHtml(__('Total Item')) ?></span>
                <span class="counter qty empty"
                      data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() },
                       blockLoader: isLoading">
                    <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                </span>
            </a>
        </div>
    <?php else: ?>
        <?php $scriptString = <<<script
            require(['jquery'], function ($) {
                $('a.action.showcart.footer').click(function() {

                });
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
     /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart-footer']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>
