<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login login-popup"  style="display:none">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Login or Create an Account')) ?></strong>
        <div class="field note"><?= $block->escapeHtml(__('If you have an account, please login.')) ?></div>
    </div>

    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    <div class="primary">
                        <div class="new-customer">
							<span><?= $block->escapeHtml(__('Not a member?')) ?></span>
							<a href="#" id="create-btn" class="action create"><?= $block->escapeHtml(__('Create an Account')) ?></a>
						</div>
                        <button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Log In')) ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div id="create-modal">
        <div class="new-customer customer-left">
            <a href="/customer/account/create" class="action create">
				<img src='<?php echo $this->getViewFileUrl('images/icon-ind-user.png'); ?>' alt="Individual">
				<p><?= $block->escapeHtml(__('Individual')) ?></p>
            </a>
        </div>
        <div class="new-customer">
            <a href="/customer/account/create?type=business" class="action create">
				<img src='<?php echo $this->getViewFileUrl('images/icon-org.png'); ?>' alt="Organization">
				<p><?= $block->escapeHtml(__('Organization')) ?></p>
            </a>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                }
            }
        }
    </script>
</div>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
				modalClass: 'account-popup'
            };

            var options2 = {
                type: 'popup',
                modalClass: 'create-account-popup',
                responsive: true,
                title: 'SELECT ACCOUNT TYPE'
            };

            var popup = modal(options, $('.login-popup'));
            $(".login-popup-btn").on('click',function(){
				$(".login-popup").modal("openModal");
            });

            var popup2 = modal(options2, $('#create-modal'));
            $("#create-btn").on('click',function(){
                $(".login-popup").modal("closeModal");
                $("#create-modal").modal("openModal");
            });
        }
    );
</script>
