<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Mage4\CategoryThumbnail\Helper\Data;
use Magento\Catalog\Helper\Output;
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
/** @var \Mage4\CategoryThumbnail\Helper\Data $helperThumbnail */
$helperThumbnail = $this->helper(Mage4\CategoryThumbnail\Helper\Data::class);
$objectManager = $helperThumbnail->getObjectManager();
$currentCategory = $block->getCurrentCategory();
?>
<?php if (!$currentCategory->getChildrenCount()): ?>
    <?php return; ?>
<?php endif; ?>

<?php
$categories = [];
$childrenIds = explode(',', $currentCategory->getChildren());

/** @var \Magento\Catalog\Model\CategoryFactory $categoryFactory */
$categoryFactory = $objectManager->create(\Magento\Catalog\Model\CategoryFactory::class);
/** @var \Magento\Store\Model\StoreManagerInterface $storeManager */
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
/** @var \Magento\Framework\Filesystem\DirectoryList $directory */
$directory = $objectManager->get('\Magento\Framework\Filesystem\DirectoryList');
$absolutePath = $directory->getRoot();
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
if (strpos($mediaUrl, 'pub') == false) {
    $absolutePath .= '/pub';
}
?>

<?php if ($_middleDescription = $block->getCurrentCategory()->getMiddleDescription()): ?>
    <div class="middle-description">
        <div class="category-middle-description">
            <?= $_middleDescription ?>
        </div>
    </div>
<?php endif; ?>

<div class="row subcategories">
    <?php foreach ($childrenIds as $subCatId): ?>
        <?php
        /** @var \Magento\Catalog\Model\Category $subCategory */
        $subCategory = $categoryFactory->create()->load($subCatId);
        $categoryImage = $mediaUrl . 'catalog/category/'. $subCategory->getThumbnail();
        if (empty($subCategory->getThumbnail()) || !@getimagesize($categoryImage)) {
            $categoryImage = $mediaUrl . 'catalog/category/no-image.jpeg';
        }
        ?>

        <div class="item">
            <div class="item-inner">
                <div class="images-content">
                    <a href="<?= $subCategory->getUrl() ?>"
                       title="<?= $subCategory->getName() ?>"
                       class="sub-category-image">
                        <img src="<?= $categoryImage ?>"
                             alt="<?= $subCategory->getName() ?>"
                        />
                    </a>
                    <div class="roll-0ver-description">
                        <span class="desc-content">
                            <p>
                                <?php
                                $description = strip_tags($subCategory->getDescription());
                                if (strlen($description) > 100) {
                                    $descriptionCut = substr($description, 0, 100);
                                    $description = substr($descriptionCut, 0, strrpos($descriptionCut, ' ')) . '...';
                                }
                                echo $description;
                                ?>
                            </p>
                            <a href="<?= $subCategory->getUrl() ?>">Explore</a>

                        </span>
                    </div>
                </div>
                <div class="box-content">
                    <h2 class="category-name">
                        <a href="<?= $subCategory->getUrl() ?>"
                           title="<?= $subCategory->getName() ?>">
                            <?= $subCategory->getName() ?>
                        </a>
                    </h2>
                    <h3 class="category-description">
                        <?php
                        $description = strip_tags($subCategory->getDescription());
                        if (strlen($description) > 50) {
                            $descriptionCut = substr($description, 0, 50);
                            $description = substr($descriptionCut, 0, strrpos($descriptionCut, ' ')) . '...';
                        }
                        echo $description;
                        ?>
                    </h3>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php if ($_bottomDescription = $block->getCurrentCategory()->getBottomDescription()): ?>
    <div class="bottom-description">
        <div class="category-bottom-description">
            <?= $_bottomDescription ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        jQuery('body').addClass('page-subcategories');
    });
</script>
