<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
$childrenIds = $block->getCurrentCategory()->getChildren();
$childrenIds = $childrenIds ? explode(',', $block->getCurrentCategory()->getChildren()) : null;

?>
<?php if (empty($childrenIds) && $block->getCurrentCategory()->getDescription()) :?>
    <div class="category-description">
        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $block->getCurrentCategory()->getDescription(),
            'description'
        ) ?>
    </div>
<?php endif; ?>
