<?php

/** @var CmsPageData $block */

use Mage4\ExtendMagentoCms\Block\CmsPageData;

$currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$baseUrl = $block->getBaseUrl();
$mediaUrl = $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl();
$urlKey = str_replace($baseUrl,"",$currentUrl);



?>
<?php if($urlKey !== ''): ?>
    <?php $cmsPageObj = $block->getCmsPageDetails($urlKey); ?>
    <?php if(count($cmsPageObj) > 0): ?>
        <?php foreach ($cmsPageObj as $key => $value): ?>
            <?php if($value->getHeroImage() || $value->getHeroImageText()): ?>
                <div class="hero-imgae-content">
                    <?php if($value->getHeroImage()): ?>
                        <img src="<?= $mediaUrl.'cms/heroimage/'.$value->getHeroImage() ?>" />
                    <?php  endif; ?>
                    <?php if($value->getHeroImageText()): ?>
                        <span class="hero-image-text"><?= $value->getHeroImageText() ?></span>
                    <?php  endif; ?>
                </div>
            <?php  endif; ?>
        <?php endforeach; ?>
    <?php  endif; ?>
<?php  endif; ?>
