<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Model\Product\ProductList\Toolbar as ToolbarModel; ?>
<?php
$generalHelper = $this->helper(Mage4\General\Helper\Data::class);
$objectManager = $generalHelper->getObjectManager();

/** @var \Magento\Catalog\Block\Product\ProductList\Toolbar $toolbar */
$toolbar = $objectManager->get(\Magento\Catalog\Block\Product\ProductList\Toolbar::class);

$label = '';
$jsonDecode = json_decode($block->getJsonConfig(), true);
if(!empty($jsonDecode['attributes'])) {
    foreach($jsonDecode['attributes'] as $eachAttr) {
        if(!empty($eachAttr['label'])) {
            $label = $eachAttr['label'];
        }
    }
}

/** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */
$productId = $block->getProduct()->getId();
/** @var \Magento\Swatches\ViewModel\Product\Renderer\Configurable $configurableViewModel */
$configurableViewModel = $block->getConfigurableViewModel()
?>
<div class="swatch-opt-<?= $block->escapeHtmlAttr($productId) ?>"
     data-role="swatch-option-<?= $block->escapeHtmlAttr($productId) ?>">
    <?php if(!empty($label)): ?>
        <label class="swatch-label"><?= $block->escapeHtml(__($label.':')) ?></label>

        <?php if($toolbar->getCurrentMode() == 'list'): ?>
            <?php $swatchToArray = json_decode($block->getJsonSwatchConfig(), true); ?>
            <?php if(!empty($swatchToArray)): ?>
                <div class="swatches-main">
                    <select class="swatch-options" id="swatch-options-clone-<?php echo $productId; ?>">
                        <?php foreach ($swatchToArray as $attr=>$eachSwatch): ?>
                            <?php $attrId = $attr; ?>
                            <?php foreach($eachSwatch as $key=>$val): ?>
                                <?php if(empty($val['label']) || empty($val['value'])): ?>
                                    <?php continue; ?>
                                <?php endif; ?>
                                <option value="<?php echo $key.'_'.$attrId; ?>" title="<?php echo $val['label']; ?>" class="swatch"><?php echo $val['value']; ?></option>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>
        <?php endif; ?>

    <?php endif; ?>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= $block->escapeJs($productId) ?>]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".product-item-details",
                "onlySwatches": true,
                "enableControlLabel": false,
                "numberToShow": <?=  $block->escapeJs($block->getNumberSwatchesPerProduct()) ?>,
                "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeJs($productId) ?>]": {
            "priceBox": {
                "priceConfig": {
                    "priceFormat": <?= /* @noEscape */ $block->getPriceFormatJson(); ?>,
                    "prices": <?= /* @noEscape */ $block->getPricesJson(); ?>
                }
            }
        }
    }
</script>

<?php
if($toolbar->getCurrentMode() == 'list'): ?>
    <script type="text/javascript">
        require([
            'jquery',
            'domReady!'
            ], function ($) {

                /*
                * hide swatches on page load
                * */
                $('.swatch-attribute.color').hide();
                // setTimeout(function() { //in case, if not hides on page load
                //     $('.swatch-attribute.color').hide();
                // }, 2000);

                $(window).load(function () {
                    $('.swatch-attribute.color').hide();
                });

                /*
                * ID starts with,
                * on change select value click swatch option
                * */
                $('select[id^="swatch-options-clone-"]').on('change', function (e) {
                    e.stopImmediatePropagation();

                    var selectedAttr = $(this).val();
                    var splitSelectedAttr = selectedAttr.split('_');
                    var swatchId = '#option-label-color-'+splitSelectedAttr[1]+'-item-'+splitSelectedAttr[0];
                    $(swatchId).trigger('click');
                    console.log(swatchId);
                });
            });
    </script>
<?php endif; ?>