<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$generalHelper = $this->helper(Mage4\General\Helper\Data::class);
$objectManager = $generalHelper->getObjectManager();/** @var \Magento\Catalog\Block\Product\ProductList\Toolbar $toolbar */
$toolbar = $objectManager->get(\Magento\Catalog\Block\Product\ProductList\Toolbar::class);
/** @var \Magento\Framework\App\RequestInterface $request */
$request = $objectManager->get(\Magento\Framework\App\RequestInterface::class);

$label = '';
$jsonDecode = json_decode($block->getJsonConfig(), true);
if(!empty($jsonDecode['attributes'])) {
    foreach($jsonDecode['attributes'] as $eachAttr) {
        if(!empty($eachAttr['label'])) {
            $label = $eachAttr['label'];
        }
    }
}
/** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */
$productId = $block->getProduct()->getId();
/** @var \Magento\Swatches\ViewModel\Product\Renderer\Configurable $configurableViewModel */
$configurableViewModel = $block->getConfigurableViewModel();
?>

<div class="swatch-opt-<?= $block->escapeHtmlAttr($productId) ?>"
     data-role="swatch-option-<?= $block->escapeHtmlAttr($productId) ?>">
    <?php if($toolbar->getCurrentMode() == 'grid' || $request->getParam('product_list_mode') == 'grid'): ?>
        <label class="swatch-label"><?= $block->escapeHtml(__($label.':')) ?></label>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= $block->escapeJs($productId) ?>]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".product-item-details",
                "onlySwatches": true,
                "enableControlLabel": false,
                "numberToShow": <?=  $block->escapeJs($block->getNumberSwatchesPerProduct()) ?>,
                "jsonConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeJs($productId) ?>]": {
            "priceBox": {
                "priceConfig": {
                    "priceFormat": <?= /* @noEscape */ $block->getPriceFormatJson(); ?>,
                    "prices": <?= /* @noEscape */ $block->getPricesJson(); ?>
                }
            }
        }
    }
</script>
