<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_QuickOrder
 */

/** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */

$product = $block->getProduct();
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
?>

<?php if ($product->isSaleable()): ?>
    <?php if (count($options)): ?>
        <fieldset class="fieldset fieldset-bundle-options">
            <?php foreach ($options as $option): ?>
                <?php
                if (!$option->getSelections()) {
                    continue;
                } else {
                    echo $block->getOptionHtml($option);
                }
                ?>
            <?php endforeach; ?>
        </fieldset>
        <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "priceBundle": {
                    "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "controlContainer": ".field.option"
                }
            }
        }
        </script>
    <?php else: ?>
        <p class="empty"><?= $block->escapeHtml(__('No options of this product are available.')) ?></p>
    <?php endif; ?>
<?php endif;?>
