<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MWishlist
 */

/** @var \Amasty\MWishlist\Block\Account\Wishlist\MassActions $block */
?>

<div class="amwishlist-toolbar-block -mass-action">
    <button class="amwishlist-button -clear -link" type="button" data-amwishlist-js="select-all">
        <?= $block->escapeHtml('Select All') ?>
    </button>
    <button class="amwishlist-button -empty -disabled" type="button" data-amwishlist-js="copy" data-mwishlist-ajax='<?= /* @noEscape */ $block->getCopyData() ?>'>
        <?= $block->escapeHtml('Copy Selected') ?>
    </button>
    <button class="amwishlist-button -empty -disabled" type="button" data-amwishlist-js="move" data-mwishlist-ajax='<?= /* @noEscape */ $block->getMoveData() ?>'>
        <?= $block->escapeHtml('Move Selected') ?>
    </button>
    <button class="amwishlist-button -fill -primary -addtolist" type="button" data-post='<?= /** @noEscape */ $block->getAddToCartData() ?>'>
        <?= $block->escapeHtml('Add All to Cart') ?>
    </button>
</div>
