<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MWishlist
 */
?>
<?php
/** @var \Amasty\MWishlist\Block\Account\Wishlist\Script $block */
?>

<script type="text/x-magento-init">
{
    "body": {
        "Amasty_MWishlist/js/multiple-wishlist": {
            <?php if (!$block->isLoggedCustomer()): ?>
            "loginUrl": "<?= $block->escapeUrl($block->getLoginUrl()) ?>",
            <?php endif; ?>
            "addItemUrl": "<?= $block->escapeUrl($block->getAddItemUrl()) ?>"
        }
    }
}
</script>
