<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MWishlist
 */
?>

<section class="amwishlist-page-title"
         data-bind="scope:'ampagetitle',
                    mageInit: {
                       'Magento_Ui/js/core/app': <?= $block->escapeHtml($block->getJsLayout()) ?>
                    }">
    <!-- ko template: getTemplate() --><!-- /ko -->
</section>
