<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_QuickOrder
 */

/* @var $block \Magento\Bundle\Block\Adminhtml\Catalog\Product\Composite\Fieldset\Options\Type\Select */
$_option      = $block->getOption();
$_selections  = $_option->getSelections();
$_default     = $_option->getDefaultSelection();
//phpcs:disable
//@phpstan-ignore-next-line
$_skipSaleableCheck = $this->helper(Magento\Catalog\Helper\Product::class)->getSkipSaleableCheck();
//phpcs:enable
list($_defaultQty, $_canChangeQty) = $block->getDefaultValues();
?>

<div class="amqorder-option-wrapper">
    <label class="amqorder-label <?= /* @noEscape */ $_option->getRequired() ? '-required' : '' ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="amqorder-option">
        <?php if ($block->showSingle()): ?>
            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   price="<?= $block->escapeHtmlAttr($block->getSelectionPrice($_selections[0])) ?>"
                   value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
        <?php else: ?>
            <select id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                    class="amqorder-select bundle option <?= /* @noEscape */ $_option->getRequired() ? 'required-entry' : '' ?>">
                <option value=""><?= $block->escapeHtml(__('Choose a selection...')) ?></option>
                <?php foreach ($_selections as $_selection): ?>
                    <option
                        value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                        <?= /* @noEscape */ $block->isSelected($_selection) ? 'selected="selected"' : '' ?>
                        <?= (!$_selection->isSaleable() && !$_skipSaleableCheck) ? ' disabled="disabled"' : '' ?>
                        price="<?= $block->escapeHtmlAttr($block->getSelectionPrice($_selection)) ?>"
                        qtyId="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
        <div class="amqorder-qty-block" data-mage-init='{"amqorderQty": {}}'>
            <input id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                   class="amqorder-input qty <?= /* @noEscape */ !$_canChangeQty ? '-disabled' : '' ?>"
                   type="number"
                   min="0"
                   name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   data-amqorder-js="input"
                   value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"/>
        </div>
    </div>
</div>
