<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<?php
$objectManager      = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession    = $objectManager->get('Magento\Customer\Model\Session');
$customerEmail      = $customerSession->getCustomer()->getCompanyEmail();
$einId              = $customerSession->getCustomer()->getEinId();
$resellerId         = $customerSession->getCustomer()->getResellerId();
$jobPosition        = $customerSession->getCustomer()->getJobPosition();
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getName()) ?><br>
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>">
                        <span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml('additional_blocks'); ?>
        <?php if ($customerEmail || $einId || $resellerId || $jobPosition): ?>
            <br><br><br>
            <div class="box box-organization">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Organization Information')) ?></span>
                </strong>
                <div class="box-content">
                    <?php if ($customerEmail): ?>
                        <p class="company_email">Company Email : <?= $customerSession->getCustomer()->getCompanyEmail() ?></p>
                    <?php endif; ?>
                    <?php if ($einId): ?>
                        <p class="ein_id">EIN ID : <?= $customerSession->getCustomer()->getEinId() ?></p>
                    <?php endif; ?>
                    <?php if ($resellerId): ?>
                        <p class="reseller_id">Reseller ID : <?= $customerSession->getCustomer()->getResellerId() ?></p>
                    <?php endif; ?>
                    <?php if ($jobPosition): ?>
                        <p class="job_position">Job Position : <?= $customerSession->getCustomer()->getJobPosition() ?></p>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
