<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>

<div class="welcome-msg">
    <h2><?php /* @escapeNotVerified */ echo __('Welcome, ') ?><strong><?php echo $block->escapeHtml($block->getName()) ?>!</strong> </h2>
</div>    
