<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MWishlist
 */


/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */
/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<a class="amwishlist-image-block"
   tabindex="-1"
   href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
   title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
    <?= $block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail')->toHtml() ?>
</a>
