<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MWishlist
 */


/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */
/** @var \Magento\Wishlist\Model\Item $item */

$item = $block->getItem();
$product = $item->getProduct();
?>

<a class="amwishlist-name"
   href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
   title="<?= $block->escapeHtmlAttr($product->getName()) ?>" >
    <?= $block->escapeHtml($product->getName()) ?>
</a>
