<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
$configProvider = $block->getData('configProvider');
?>


<div class="block block-search">
    <div class="block block-title"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
    <div class="btn-login">
        <?php echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header_login')
        ->toHtml();
        ?>
    </div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form"
              action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input id="search"
                            <?php if ($configProvider->isSuggestionsAllowed()):?>
                               data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                                    "destinationSelector":"#search_autocomplete",
                                    "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                               }'
                            <?php endif;?>
                           type="text"
                           name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
                           class="input-text"
                           maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
                <div class="password-option">
                    <span><?= $block->escapeHtml(__('#Type atleast 8 character to search')) ?></span>
                    <span style="margin-left:20px;"><?= $block->escapeHtml(__('#Hit enter to search')) ?></span>           
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                    title="<?= $block->escapeHtml(__('Search')) ?>"
                    class="action search"
                    aria-label="Search"
                >
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </button>
                <button 
                    title="<?= $block->escapeHtml(__('Close')) ?>"
                    class="action close"
                    aria-label="Close"
                >
                    <span><?= $block->escapeHtml(__('Close')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
	require([
		'jquery'
			], function ($) {
				$(document).ready(function(){
					jQuery(document).on("click", ".block-title", function(){
                        if(jQuery(this).parent('.block-search').hasClass('active')){
                            jQuery(this).parent('.block-search').removeClass('active');
                        }else{
                            jQuery(this).parent('.block-search').addClass('active');
                        }
                    });
                    jQuery("button.action.close").on("click", function(){
                        jQuery("div.block.block-search.active").removeClass('active');
                    });
                });
            }); 
</script>