<?php $_orders = $block->getPackingSlipsList() ?>
?>
<div class="table-wrapper orders-packing">
    <table class="data table table-order-items packing" id="packing-orders-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Packing Slips')) ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Shipment #') ?></th>
            <th scope="col" class="col shipment-date"><?= /* @escapeNotVerified */ __('Shipment Date') ?></th>
            <th scope="col" class="col ord-id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
            <th scope="col" class="col track-number"><?= /* @escapeNotVerified */ __('Track Number') ?></th>
            <th scope="col" class="col title"><?= /* @escapeNotVerified */ __('Title') ?></th>
            <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_orders as $_order): ?>
            <?php $tracksCollection = $_order->getTracksCollection(); ?>
            <?php foreach ($tracksCollection->getItems() as $track): ?>
                <tr>
                    <td data-th="<?= /* @escapeNotVerified */ __('Shipment #') ?>" class="col id"><?= str_pad($track->getEntityId(), 9, '0', STR_PAD_LEFT) ?></td>
                    <td data-th="<?= /* @escapeNotVerified */ __('Shipment Date') ?>" class="col shipment-date"><?= $block->formatDate($track->getCreatedAt()) ?></td>
                    <td data-th="<?= /* @escapeNotVerified */ __('Order #') ?>" class="col ord-id"><?= str_pad($_order->getEntityId(), 9, '0', STR_PAD_LEFT) ?></td>
                    <td data-th="<?= /* @escapeNotVerified */ __('Track Number') ?>" class="col track-number"><?= $track->getTrackNumber() ?></td>
                    <td data-th="<?= /* @escapeNotVerified */ __('Title') ?>" class="col track-title"><?= $track->getTitle() ?></td>
                    <td data-th="<?= /* @escapeNotVerified */ __('Action') ?>" class="col actions">
                        <a href="<?= /* @escapeNotVerified */ $block->getViewTracksUrl($_order->getEntityId()) ?>"
                           class="action view">
                            <span><?= /* @escapeNotVerified */ __('View') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

