<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_CancelOrder
 */
?>
<?php
/**
 * Amasty Cancel Orders PopUp template
 *
 * @var \Amasty\CancelOrder\Block\Popup $block
 */

$reasons = $block->getReasons();
?>

<main class="amcorder-main"
      style="display: none;"
      data-mage-init='{"amcorderPopUp": {"trigger": "[data-amcorder-js=cancel-<?= (int)$block->getOrder()->getId() ?>]"}}'>
    <h4 class="amcorder-notice">
        <?= $block->escapeHtml($block->getNotice())?>
    </h4>
    <form class="amcorder-form"
          data-mage-init='{"validation": {}}'
          action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
          data-amcorder-js="form"
          method="post">
        <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey())?>">
        <input name="order_id" type="hidden" value="<?= $block->escapeHtml($block->getOrder()->getId()) ?>">

        <?php if ($reasons): ?>
            <label class="amcorder-label<?= /* @noEscape */ $block->isElementRequired('reason') ? ' -required' : '' ?>"
                   for="amcorder-select">
                <span><?= $block->escapeHtml(__('Choose a Reason for Order Cancellation')); ?></span>
            </label>
            <select id="amcorder-select"
                    class="amcorder-select"
                    <?= /* @noEscape */ $block->isElementRequired('reason') ? 'data-validate="{required:true}"' : '' ?>
                    name="reason">
                <option value=""><?= $block->escapeHtml(__('Choose a reason...')); ?></option>
                <?php foreach ($reasons as $reason): ?>
                    <option value="<?= $block->escapeHtml($reason); ?>">
                        <?= $block->escapeHtml($reason); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
        <label class="amcorder-label<?= /* @noEscape */ $block->isElementRequired('comment') ? ' -required' : '' ?>"
               for="amcorder-textarea">
            <span><?= $block->escapeHtml(__('Leave a Comment')); ?></span>
        </label>
        <textarea id="amcorder-textarea"
                  class="amcorder-textarea"
                  name="comment"
                  data-validate="{'validate-no-html-tags':true<?= /* @noEscape */ $block->isElementRequired('comment') ? ', required:true' : '' ?>}"
                  rows="5"
                  cols="25"></textarea>
    </form>
</main>
